### ISSUE TITLE
CMake Error at cmake_install.cmake

### ISSUE THREAD

**Issue by ZzhengP** [syroco/traxxs_orca#2]
![image](https://user-images.githubusercontent.com/36111459/41646275-a4f83970-7473-11e8-92b0-ca4299d431d6.png)
file install cannot find. 

Pu

**Comment by ZzhengP** [comment]
Create config directory in traxxs_orca, and fixed this problem.

**Comment by ahoarau** [comment]
Fixed in https://github.com/syroco/traxxs_orca/commit/035341bc4e4525d5604eb0529b872fcb314db613
Thanks !
